### ISSUE TITLE
Parsing issues with German locations.

### ISSUE THREAD

**Issue by erunion** [erunion/showtimes#6]
http://google.com/movies?near=Goebelstr.+11%2C+64293+Darmstadt%2C+Germany+-+06151+8705868

```
Maleficent - Die dunkle Fee info= [ '‎1hr 36min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Das Schicksal ist ein mieser Verr�ter info= [ '‎2hr 6min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Tinkerbell und die Piratenfee info= [ '‎1hr 18min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
A Million Ways to Die in the West info= [ '‎1hr 56min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
X-Men: Zukunft ist Vergangenheit info= [ '‎2hr 12min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Das magische Haus info= [ '‎1hr 25min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
About Last Night info= [ '‎1hr 40min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Die Monster Uni info= [ '‎1hr 44min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
WM 2014: Italien - Costa Rica info= [ '‎‎' ]
WM 2014: Schweiz - Frankreich info= [ '‎‎' ]
Maleficent - Die dunkle Fee info= [ '‎1hr 36min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Maleficent - Die dunkle Fee info= [ '‎1hr 36min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Tinkerbell und die Piratenfee info= [ '‎1hr 18min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
Das magische Haus info= [ '‎1hr 25min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
Bad Neighbors info= [ '‎1hr 37min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Edge of Tomorrow info= [ '‎1hr 53min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Einmal Hans mit scharfer So�e info= [ '‎1hr 36min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Die Schadenfreundinnen info= [ '‎1hr 49min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Cuban Fury info= [ '‎1hr 38min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Nix wie weg - vom Planeten Erde info= [ '‎1hr 29min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
Die zwei Gesichter des Januars info= [ '‎1hr 37min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Bibi & Tina - Der Film info= [ '‎1hr 41min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
Grace of Monaco info= [ '‎1hr 42min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
Muppets Most Wanted info= [ '‎1hr 48min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
Free Birds info= [ '‎1hr 32min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Transcendence info= [ '‎2hr 0min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Maleficent - Die dunkle Fee info= [ '‎1hr 36min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Tinkerbell und die Piratenfee info= [ '‎1hr 18min‎‎', 'Rated Ohne Altersbeschr�nkung‎' ]
Edge of Tomorrow info= [ '‎1hr 53min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Boyhood info= [ '‎2hr 46min‎‎', 'Rated Freigegeben ab 6 Jahren‎' ]
Zoran - Mein Neffe, der Idiot info= [ '‎1hr 53min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Maman und ich info= [ '‎1hr 27min‎‎', 'Rated Freigegeben ab 12 Jahren‎' ]
Die unersch�tterliche Liebe der Suzanne info= [ '‎1hr 34min‎' ]

TypeError: Cannot call method 'match' of undefined
    at Object.<anonymous> (/Users/erunion/code/showtimes/index.js:124:23)
    at exports.each (/Users/erunion/code/showtimes/node_modules/cheerio/lib/api/traversing.js:267:24)
    at Object.<anonymous> (/Users/erunion/code/showtimes/index.js:109:41)
    at exports.each (/Users/erunion/code/showtimes/node_modules/cheerio/lib/api/traversing.js:267:24)
    at Request._callback (/Users/erunion/code/showtimes/index.js:93:19)
    at Request.self.callback (/Users/erunion/code/showtimes/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/erunion/code/showtimes/node_modules/request/request.js:985:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/erunion/code/showtimes/node_modules/request/request.js:936:12)
```

With this, apparently it's possible for a movie entry to not have an `info` datapoint.

**Comment by erunion** [comment]
No longer seeing this happening.
